### ISSUE TITLE
Documentar guia de uso do projeto

### ISSUE THREAD

**Issue by thiagorpereira** [fga-eps-mds/2019.2-Vsign#43]
### Descrição 
Criar documento de guia de uso do projeto

## Tasks

- [x] Inserir guia de instalação do docker e docker-compose
- [x] Descrever comandos para rodar o projeto
- [x] Descrever comandos para ser usado enquanto o ambiente está em execução
- [x] Documentação deve estar no README.md
